-- go to `qb-core\shared\items.lua` and add this

 -- vehicle craft
["pneu"]             	 = {["name"] = "pneu",         			["label"] = "Pneu",    		["weight"] = 10,       ["type"] = "item",      ["image"] = "tire.png",         		["unique"] = false,     ["useable"] = true,     ["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Parece um pneu..."},
["bateria_veiculo"]         	     = {["name"] = "bateria_veiculo",         		["label"] = "Bateria de Veículo",    			["weight"] = 10,       ["type"] = "item",      ["image"] = "battery.png",     	    ["unique"] = false,     ["useable"] = true,     ["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Uma bateria usada para alimentar veículos motorizados. Não tenho certeza se ainda tem carga."},
["transmissao"]         	 	 = {["name"] = "transmissao",         		["label"] = "Transmissão",    			["weight"] = 10,       ["type"] = "item",      ["image"] = "gear.png",     		["unique"] = false,     ["useable"] = true,     ["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Uma transmissão manual de veículo."},
["velas_ignicao"]             	 = {["name"] = "velas_ignicao",         		["label"] = "Velas de Ignição",    			["weight"] = 10,       ["type"] = "item",      ["image"] = "sparkplugs.png",           ["unique"] = false,     ["useable"] = true,     ["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Peça do carro que gera faísca elétrica para o motor funcionar..."},
["roda"]             		 = {["name"] = "roda",         			["label"] = "Roda",    			["weight"] = 10,       ["type"] = "item",      ["image"] = "rim.png",         		["unique"] = false,     ["useable"] = true,     ["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Você precisa disso para segurar o pneu."},
["motor_veiculo"]         	 	 = {["name"] = "motor_veiculo",         		["label"] = "Motor de Veículo",    			["weight"] = 10,      ["type"] = "item",      ["image"] = "carengine.png",     		["unique"] = false,     ["useable"] = true,     ["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Necessário se você está craftando um carro com motor!"},
['electronicscrap'] 			 = {['name'] = 'electronicscrap', 			    ['label'] = 'Sucata Eletrônica', 		['weight'] = 10, 		['type'] = 'item', 		['image'] = 'electronics.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'Fios e uma placa de circuito, bom para craft de veículo?'}, 
["chassi_moto"]         	 	 = {["name"] = "chassi_moto",         		["label"] = "Chassi de Moto",    			["weight"] = 10,      ["type"] = "item",      ["image"] = "cycleframe.png",     		["unique"] = false,     ["useable"] = true,     ["shouldClose"] = true,    ["combinable"] = nil,   ["description"] = "Necessário se você está craftando uma moto!"},
['chassi_veiculo'] 			 = {['name'] = 'chassi_veiculo', 			    ['label'] = 'Chassi de Veículo', 		['weight'] = 10, 		['type'] = 'item', 		['image'] = 'vehicleframe.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = false,   ['combinable'] = nil,   ['description'] = 'Necessário se você está craftando um veículo!'}, 
